- id: '1581658502624'
  alias: Garage Door
  description: ''
  trigger:
  - entity_id: cover.garage_door
    for: 00:10:00
    from: closed
    platform: state
    to: open
  condition: []
  action:
  - data:
      message: 'Garage Door open: 10 min'
    service: telegram_bot.send_message